blank_issues_enabled: false
contact_links:
  - name: 🤷 Q&A / Help
    url: https://github.com/thekaifansari01/Jarvis-OS-Agent/discussions/categories/q-a
    about: Please ask general questions or get help in the Discussions Q&A section.
  - name: 📖 Documentation
    url: https://github.com/thekaifansari01/Jarvis-OS-Agent#readme
    about: Check out the README before opening an issue.