import os
from dotenv import load_dotenv
load_dotenv()

GROQ_ROUTER_MODEL = "llama-3.1-8b-instant"
GROQ_FAST_MODEL = "llama-3.3-70b-versatile"
GROQ_SUMMARY_MODEL = "openai/gpt-oss-120b"
GROQ_WHISPER_MODEL = "whisper-large-v3"
GROQ_EMAIL_SUMMARY_MODEL = "llama-3.1-8b-instant"
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

GEMINI_AGENT_MODEL = "gemma-4-31b-it"
GEMINI_DEEP_RESEARCH_MODEL = "gemma-4-31b-it"
GEMINI_EMBEDDING_MODEL = "gemini-embedding-2"
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

FLUX_IMAGE_MODEL = "black-forest-labs/FLUX.1-schnell"
TOGETHER_API_KEY = os.getenv("TOGETHER_AI")

AI_HORDE_IMAGE_MODEL = "AlbedoBase XL (SDXL)"

EDGE_TTS_VOICE = "hi-IN-MadhurNeural"

EMBEDDING_DIM = 768
WHISPER_ENERGY_THRESHOLD = 400
WHISPER_PAUSE_THRESHOLD = 0.5
WHISPER_LISTEN_TIMEOUT = 4
WHISPER_PHRASE_TIME_LIMIT = 10
DEEP_RESEARCH_TIMEOUT = 420
EMAIL_SUMMARY_MAX_TOKENS = 40

TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
PICOVOICE_API_KEY = os.getenv("PICOVOICE_API_KEY")
TWILIO_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_FROM = os.getenv("TWILIO_FROM_NUMBER")

CONFIG = {
    "AGENT_MAX_STEPS": 20,
    "AGENT_TIMEOUT": 900,
    "AGENT_RETRY_LIMIT": 2,
    "AGENT_SCRATCHPAD_MAX_CHARS": 500000,
}